Test – PYREMB
Test Program
Christian Schwermann
15/03/2019
100 statements
Source File
Uses
Precision_mod
Types_mod
System_mod
Utils_mod
Xcpot_mod
Test of most of the functions and subroutines, just to see if they work / are correct
Calls
Contents
Variables
ngpt natoms i dens vnuc q pos cell dens2 mol1 mol2 mol3 grid1 ener pot positions1 positions2 func res_func
Variables
Type Attributes Name Initial
integer :: ngpt
number of grid points, number of atoms, loop index
integer :: natoms
number of grid points, number of atoms, loop index
integer :: i
number of grid points, number of atoms, loop index
real(kind=DP) :: dens(1:3)
density, nuclear potential, ion charges, ion positions, cell, another density
real(kind=DP) :: vnuc(1:3)
density, nuclear potential, ion charges, ion positions, cell, another density
real(kind=DP) :: q(1:4)
density, nuclear potential, ion charges, ion positions, cell, another density
real(kind=DP) :: pos(1:3,1:4)
density, nuclear potential, ion charges, ion positions, cell, another density
real(kind=DP) :: cell(1:3,1:3)
density, nuclear potential, ion charges, ion positions, cell, another density
real(kind=DP) :: dens2(1:2)
density, nuclear potential, ion charges, ion positions, cell, another density
type(molecule_t) :: mol1
three molecules
type(molecule_t) :: mol2
three molecules
type(molecule_t) :: mol3
three molecules
type(grid_t) :: grid1
grid
real(kind=DP) :: ener
dft energy and effective potential
real(kind=DP) :: pot(1:3)
dft energy and effective potential
real(kind=DP) :: positions1(1:3,1:4)
grid positions for two grids, reference and result function for interpolation test
real(kind=DP) :: positions2(1:3,1:5)
grid positions for two grids, reference and result function for interpolation test
real(kind=DP) :: func(1:4)
grid positions for two grids, reference and result function for interpolation test
real(kind=DP) :: res_func(1:5)
grid positions for two grids, reference and result function for interpolation test
Call graph
test calls mol_set_grid, ions_has_charges, mol_has_vnuc, mol_set_spin, mol_set_density, mol_has_grid, mol_has_density, sys_init, mol_set_vnuc, mol_has_ions, mol_set_ions, mol_set_gradient, mol_has_gradient, xc_energy, xc_potential, mol_init_ions, integrate, shepard_interpolate, mol_init_grid
mol_set_grid calls mol_has_grid
mol_set_spin calls mol_has_density, mol_has_gradient, warning
mol_set_density calls mol_has_density
mol_set_vnuc calls mol_has_vnuc
mol_set_ions calls mol_has_ions
mol_set_gradient calls mol_has_gradient
xc_energy calls mol_has_gradient, integrate, error, xc_parse, xc_ener
xc_potential calls mol_has_gradient, error, xc_parse, xc_pot
mol_init_ions calls mol_has_ions, ions_set_positions, ions_set_charges
integrate calls grid_has_weights, grid_volume, grid_has_cell
mol_init_grid calls mol_has_grid, grid_set_positions, grid_set_cell, grid_set_weights
ions_set_positions calls ions_has_positions
ions_set_charges calls ions_has_charges
grid_set_positions calls grid_has_positions
grid_set_cell calls error, grid_has_cell, grid_set_points_xyz
grid_set_weights calls grid_has_weights
grid_volume calls grid_has_cell, cross