Cross – PYREMB
Cross Function
7 statements
Source File
public pure function Cross(a, b) result(c)
Calculation of the cross product of two vectors
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: a(1:3)
Input: two 3D vectors
real(kind=DP), intent(in) :: b(1:3)
Input: two 3D vectors
Return Value real(kind=DP) (1:3)
Output: one 3D vector
Called by
Contents
None
Call graph
grid_volume calls cross
integrate calls grid_volume
embedding_energy calls integrate
xc_energy calls integrate
test calls integrate, xc_energy