Embedding_energy – PYREMB
Embedding_energy Subroutine
45 statements
Source File
public subroutine Embedding_energy(x_func, c_func, k_func, energy)
Calculation of embedding energy for the global system.
Only needs eXchange, Correlation and Kinetic functionals as input and returns the effective embedding energy on the active grid
Todo
calculate energy on a common supergrid
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: x_func
Input: exchange functional
character(len=*), intent(in) :: c_func
Input: correlation functional
character(len=*), intent(in) :: k_func
Input: kinetic functional
real(kind=DP), intent(out) :: energy
Output: embedding potential
Calls
Contents
None
Call graph
embedding_energy calls error, xc_energy, mol_interpolate, integrate, mol_has_vnuc, mol_set_vnuc, mol_set_density
mol_interpolate calls error, grid_has_periodicity, mol_has_grid, mol_has_vnuc, mol_has_gradient, mol_set_density_b, mol_set_gradient, shepard_interpolate, mol_has_density, grid_pos_from_cell, mol_set_gradient_aa, mol_set_gradient_bb, mol_set_density, mol_set_density_a, mol_set_gradient_ab, mol_set_grid, grid_has_positions, mol_set_vnuc
integrate calls grid_has_weights, grid_has_cell, grid_volume
grid_has_periodicity calls grid_has_cell, grid_has_points_xyz
mol_set_density_b calls mol_has_density
mol_set_gradient calls mol_has_gradient
grid_pos_from_cell calls grid_has_periodicity, grid_set_positions
mol_set_gradient_aa calls mol_has_gradient
mol_set_gradient_bb calls mol_has_gradient
mol_set_density calls mol_has_density
grid_volume calls grid_has_cell, cross
mol_set_density_a calls mol_has_density
mol_set_gradient_ab calls mol_has_gradient
mol_set_grid calls mol_has_grid
mol_set_vnuc calls mol_has_vnuc
grid_set_positions calls grid_has_positions