Error – PYREMB
Error Subroutine
11 statements
Source File
public subroutine Error(string, int1, int2, real1, real2)
Throw an Error determined by a string, print some numbers and exit with non-zero status
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Input: string describing the error
integer, intent(in), optional :: int1
Input: integers to print out, optional
integer, intent(in), optional :: int2
Input: integers to print out, optional
real(kind=DP), intent(in), optional :: real1
Input: floats to print out, optional
real(kind=DP), intent(in), optional :: real2
Input: floats to print out, optional
Called by
Contents
None
Call graph
xc_pot calls error
embedding_energy calls error, mol_interpolate
xc_potential calls error
embedding_potential calls error, mol_interpolate
grid_set_cell calls error
xc_ener calls error
mol_interpolate calls error
xc_energy calls error
mol_init_grid calls grid_set_cell
test calls xc_potential, xc_energy, mol_init_grid