Grid_set_points_xyz – PYREMB
Grid_set_points_xyz Subroutine
9 statements
Source File
public subroutine Grid_set_points_xyz(this, ngptx, ngpty, ngptz)
Set the x y and z points of a grid.
Arguments
Type Intent Optional Attributes Name
type(grid_t), intent(inout) :: this
Input: grid
integer, intent(in) :: ngptx
Input: grid points in each direction
integer, intent(in) :: ngpty
Input: grid points in each direction
integer, intent(in) :: ngptz
Input: grid points in each direction
Called by
Contents
None
Call graph
grid_set_cell calls grid_set_points_xyz
mol_init_grid calls grid_set_cell
test calls mol_init_grid