Grid_has_positions – PYREMB
Grid_has_positions Function
5 statements
Source File
public pure function Grid_has_positions(this) result(haspositions)
Return .true. if the grid has positions.
Arguments
Type Intent Optional Attributes Name
type(grid_t), intent(in) :: this
Input: grid
Return Value logical
Output: whether the grid has a cell
Called by
Contents
None
Call graph
mol_interpolate calls grid_has_positions, grid_pos_from_cell
grid_set_positions calls grid_has_positions
mol_init_grid calls grid_set_positions
grid_pos_from_cell calls grid_set_positions
embedding_energy calls mol_interpolate
embedding_potential calls mol_interpolate
test calls mol_init_grid