Grid_volume – PYREMB
Grid_volume Function
8 statements
Source File
public function Grid_volume(grid) result(volume)
Calculation of the volume of the cell associated with a given grid.
Arguments
Type Intent Optional Attributes Name
type(grid_t), intent(in) :: grid
Input: grid, has to have a cell
Return Value real(kind=DP)
Output: the calculated volume
Calls
Called by
Contents
None
Call graph
grid_volume calls cross, grid_has_cell
integrate calls grid_volume
xc_energy calls integrate
test calls integrate, xc_energy
embedding_energy calls integrate