Grid_has_cell – PYREMB
Grid_has_cell Function
5 statements
Source File
public pure function Grid_has_cell(this) result(hascell)
Return .true. if the grid has a cell.
Arguments
Type Intent Optional Attributes Name
type(grid_t), intent(in) :: this
Input: grid
Return Value logical
Output: whether the grid has a cell
Called by
Contents
None
Call graph
grid_has_periodicity calls grid_has_cell
grid_set_cell calls grid_has_cell
grid_volume calls grid_has_cell
integrate calls grid_has_cell, grid_volume
grid_pos_from_cell calls grid_has_periodicity
test calls integrate, xc_energy, mol_init_grid
mol_interpolate calls grid_has_periodicity, grid_pos_from_cell
xc_energy calls integrate
embedding_energy calls integrate, mol_interpolate
mol_init_grid calls grid_set_cell
embedding_potential calls mol_interpolate