Grid_pos_from_cell – PYREMB
Grid_pos_from_cell Subroutine
18 statements
Source File
public subroutine Grid_pos_from_cell(grid)
Calculation of grid positions from cell vectors and grid points.
Note
here, x is the fastest dimension, this is different for cube files, where z is fastest, thus, reading cubes and converting into our format will be slow
Arguments
Type Intent Optional Attributes Name
type(grid_t), intent(inout) :: grid
Input: grid, has to have a cell
Calls
Called by
Contents
None
Call graph
grid_pos_from_cell calls grid_has_periodicity, grid_set_positions
grid_has_periodicity calls grid_has_cell, grid_has_points_xyz
grid_set_positions calls grid_has_positions
mol_interpolate calls grid_pos_from_cell
embedding_energy calls mol_interpolate
embedding_potential calls mol_interpolate