Integrate – PYREMB
Integrate Function
26 statements
Source File
public function Integrate(array, grid) result(integral)
Integration of arbitrary functions on arbitrary grids.
This is simply a sum, i. e. when weights are given and else.
Here array is , grid%weights is , ngpot is .
Todo
Specific method for cells
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: array(:)
Input: any array
type(grid_t), intent(in), optional :: grid
Input: grid, has to have the same number of points as the array
Return Value real(kind=DP)
Output: the calculated integral
Calls
Called by
Contents
None
Call graph
integrate calls grid_has_cell, grid_volume, grid_has_weights
grid_volume calls grid_has_cell, cross
test calls integrate, xc_energy
xc_energy calls integrate
embedding_energy calls integrate