Mol_has_density – PYREMB
Mol_has_density Function
5 statements
Source File
public pure function Mol_has_density(this) result(hasdensity)
Return .true. if the molecule has a density.
Arguments
Type Intent Optional Attributes Name
type(molecule_t), intent(in) :: this
Input: molecule
Return Value logical
Output: whether the molecule has a density
Called by
Contents
None
Call graph
mol_set_density calls mol_has_density
mol_set_spin calls mol_has_density
mol_interpolate calls mol_has_density, mol_set_density, mol_set_density_a, mol_set_density_b
mol_set_density_a calls mol_has_density
mol_set_density_b calls mol_has_density
test calls mol_has_density, mol_set_density, mol_set_spin
embedding_energy calls mol_interpolate
embedding_potential calls mol_interpolate