Mol_interpolate – PYREMB
Mol_interpolate Subroutine
56 statements
Source File
public subroutine Mol_interpolate(molecule, ingrid)
Interpolation of all functions in a molecule onto some grid.
This subroutine interpolates density, gradient and nuclear potential of a molecule onto a given grid. An implementation of Shepards method is used.
Arguments
Type Intent Optional Attributes Name
type(molecule_t), intent(inout) :: molecule
Input: molecule, will be modified
type(grid_t), intent(in) :: ingrid
Input: grid
Calls
Called by
Contents
None
Call graph
mol_interpolate calls grid_has_periodicity, mol_set_density, mol_set_gradient_aa, error, grid_has_positions, shepard_interpolate, mol_has_density, mol_set_gradient_ab, mol_set_density_a, mol_set_gradient_bb, mol_has_gradient, mol_set_density_b, mol_set_vnuc, mol_set_gradient, mol_set_grid, grid_pos_from_cell, mol_has_grid, mol_has_vnuc
grid_has_periodicity calls grid_has_points_xyz, grid_has_cell
mol_set_density calls mol_has_density
mol_set_gradient_aa calls mol_has_gradient
mol_set_gradient_ab calls mol_has_gradient
mol_set_density_a calls mol_has_density
mol_set_gradient_bb calls mol_has_gradient
mol_set_density_b calls mol_has_density
mol_set_vnuc calls mol_has_vnuc
mol_set_gradient calls mol_has_gradient
mol_set_grid calls mol_has_grid
grid_pos_from_cell calls grid_has_periodicity, grid_set_positions
grid_set_positions calls grid_has_positions
embedding_energy calls mol_interpolate
embedding_potential calls mol_interpolate