Mol_has_grid – PYREMB
Mol_has_grid Function
5 statements
Source File
public pure function Mol_has_grid(this) result(hasgrid)
Return .true. if the molecule has a grid.
Arguments
Type Intent Optional Attributes Name
type(molecule_t), intent(in) :: this
Input: molecule
Return Value logical
Output: whether the molecule has a grid
Called by
Contents
None
Call graph
mol_set_grid calls mol_has_grid
test calls mol_has_grid, mol_set_grid, mol_init_grid
mol_interpolate calls mol_has_grid, mol_set_grid
mol_init_grid calls mol_has_grid
embedding_potential calls mol_interpolate
embedding_energy calls mol_interpolate