Mol_init_grid – PYREMB
Mol_init_grid Subroutine
18 statements
Source File
public subroutine Mol_init_grid(this, weights, cell, positions)
Initialize the grid of a molecule. This requires nothing, but accepts weights, cell information and grid positions.
Arguments
Type Intent Optional Attributes Name
type(molecule_t), intent(inout) :: this
Input: molecule
real(kind=DP), intent(in), optional :: weights(:)
Input: grid weights, size ngpt
real(kind=DP), intent(in), optional :: cell(:,:)
Input: unit cell, size (3, 3)
real(kind=DP), intent(in), optional :: positions(:,:)
Input: grid weights, size (3, ngpt); first index is x, y, z
Calls
Called by
Contents
None
Call graph
mol_init_grid calls grid_set_weights, grid_set_cell, mol_has_grid, grid_set_positions
grid_set_weights calls grid_has_weights
grid_set_cell calls error, grid_has_cell, grid_set_points_xyz
grid_set_positions calls grid_has_positions
test calls mol_init_grid