Mol_has_gradient – PYREMB
Mol_has_gradient Function
5 statements
Source File
public pure function Mol_has_gradient(this) result(hasgradient)
Return .true. if the molecule has a density gradient.
Arguments
Type Intent Optional Attributes Name
type(molecule_t), intent(in) :: this
Input: molecule
Return Value logical
Output: whether the molecule has a gradient
Called by
Contents
None
Call graph
xc_potential calls mol_has_gradient
test calls mol_has_gradient, xc_potential, xc_energy, mol_set_gradient, mol_set_spin
mol_interpolate calls mol_has_gradient, mol_set_gradient, mol_set_gradient_aa, mol_set_gradient_bb, mol_set_gradient_ab
xc_energy calls mol_has_gradient
mol_set_gradient calls mol_has_gradient
mol_set_gradient_aa calls mol_has_gradient
mol_set_gradient_bb calls mol_has_gradient
mol_set_spin calls mol_has_gradient
mol_set_gradient_ab calls mol_has_gradient
embedding_potential calls mol_interpolate
embedding_energy calls mol_interpolate