Shepard_interpolate – PYREMB
Shepard_interpolate Subroutine
31 statements
Source File
public subroutine Shepard_interpolate(ref_pos, ref_func, pos, func)
Shepard interpolation of a 3D function given on positions onto a grid defined by positions .
This is the basic, global Shepard method: with and
ref_pos is , ref_func is , pos is and func is .
Ref.: Shepard D (1968) A two-dimensional interpolation function for irregularly spaced data Proc. 23rd Nat. Conf. ACM 517-523 Brandon/Systems Press Inc., Princeton DOI: https://dx.doi.org/10.1145/800186.810616
Note
Might need to rescale everything if the integral has to be the same!
Arguments
Type Intent Optional Attributes Name
real(kind=DP), intent(in) :: ref_pos(:,:)
Input: reference position and target position
real(kind=DP), intent(in) :: ref_func(:)
Input: reference function
real(kind=DP), intent(in) :: pos(:,:)
Input: reference position and target position
real(kind=DP), intent(out) :: func(:)
Output: interpolated function
Called by
Contents
None
Call graph
test calls shepard_interpolate
mol_interpolate calls shepard_interpolate
embedding_energy calls mol_interpolate
embedding_potential calls mol_interpolate