Xc_potential – PYREMB
Xc_potential Subroutine
19 statements
Source File
public subroutine Xc_potential(molecule, functional, potential)
Arguments
Type Intent Optional Attributes Name
type(molecule_t), intent(in) :: molecule
character(len=*), intent(in) :: functional
real(kind=DP), intent(out) :: potential(:)
Calls
Called by
Contents
None
Call graph
xc_potential calls xc_parse, error, mol_has_gradient, xc_pot
test calls xc_potential