Xc_pot – PYREMB
Xc_pot Subroutine
30 statements
Source File
public subroutine Xc_pot(functional, ngpt, spinpol, potential, density, gradient)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: functional
integer, intent(in) :: ngpt
logical, intent(in) :: spinpol
real(kind=DP), intent(out) :: potential(:)
real(kind=DP), intent(in) :: density(:)
real(kind=DP), intent(in), optional :: gradient(:)
Calls
Contents
None
Call graph
xc_pot calls xc_f90_func_init, error, xc_f90_func_end, xc_f90_info_family