Mol_has_vnuc – PEREMB
Mol_has_vnuc Function
5 statements
Source File
public pure function Mol_has_vnuc(this) result(hasvnuc)
Return .true. if the molecule has a vnuc (nuclear potential).
Arguments
Type Intent Optional Attributes Name
type(molecule_t), intent(in) :: this
Input: molecule
Return Value logical
Output: whether the molecule has a vnuc
Called by
Contents
None
Call graph
test calls mol_has_vnuc, mol_set_vnuc
mol_interpolate calls mol_has_vnuc, mol_set_vnuc
mol_set_vnuc calls mol_has_vnuc