Xc_energy – PEREMB
Xc_energy Subroutine
22 statements
Source File
public subroutine Xc_energy(molecule, functional, energy)
Arguments
Type Intent Optional Attributes Name
type(molecule_t), intent(in) :: molecule
character(len=*), intent(in) :: functional
real(kind=DP), intent(out) :: energy
Calls
Called by
Contents
None
Call graph
xc_energy calls mol_has_gradient, xc_ener, error, xc_parse, integrate
integrate calls grid_has_weights
test calls xc_energy